sudo: false
language: ruby
before_install:
  - npm install -g geojsonhint
cache: bundler
branches:
  only:
    - master
rvm:
  - 2.1
script:
  - bundle exec httparty -f json "http://geojsonlint.com/validate?url=https://raw.githubusercontent.com/geobrando/sandbox/master/tests/geojson/good.geojson"
  - bundle exec httparty -f json "http://geojsonlint.com/validate?url=https://raw.githubusercontent.com/geobrando/sandbox/master/tests/geojson/bad.geojson"
  - pwd
  - ls
  #- cd geobrando/sandbox/tests/geojson 
  #- geojsonhint --json good.geojson
  3- geojsonhint --json bad.geojson
