sudo: false
language: ruby
cache: bundler
branches:
  only:
    - master
rvm:
  - 2.1
script:
  - bundle exec httparty -f json http://geojsonlint.com/validate?url=https://raw.githubusercontent.com/geobrando/sandbox/master/tests/geojson/good.geojson"
  - bundle exec httparty -f json http://geojsonlint.com/validate?url=https://raw.githubusercontent.com/geobrando/sandbox/master/tests/geojson/bad.geojson"
