sudo: false
language: ruby
before_install:
  - npm install -g geojsonhint
cache: bundler
branches:
  only:
    - master
rvm:
  - 2.1
script:
  - bundle exec httparty -f json "http://geojsonlint.com/validate?url=https://raw.githubusercontent.com/geobrando/sandbox/master/tests/geojson/good.geojson"
  - bundle exec httparty -f json "http://geojsonlint.com/validate?url=https://raw.githubusercontent.com/geobrando/sandbox/master/tests/geojson/bad.geojson"
  - result=$(geojsonhint --json < tests/geojson/good.geojson); echo "$result"; if grep -qF '"error":' <<< "$result"; then exit 1; fi
  - result=$(geojsonhint --json < tests/geojson/bad.geojson); echo "$result"; if grep -qF '"error":' <<< "$result"; then exit 1; fi
