baseurl: /sandbox
permalink: pretty
markdown: kramdown
paginate: 5
repo: sandbox
github_org: maptime
maptime:
  chapter: Maptime HQ
  twitter: maptimehq
  #disqus: YOUR DISQUS USERNAME 

excerpt_separator: <!--more-->
exclude: [vendor]